<a href="https://colab.research.google.com/github/LaxmiPrasannaVollala/ICP_1/blob/main/ICP_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/datasets/hepatitis/master/data/hepatitis.csv')
df.head(10)

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.0,85.0,18.0,4.0,NaN,False,live
1,50,female,False,False,True,False,False,False,False,False,False,False,False,0.9,135.0,42.0,3.5,NaN,False,live
2,78,female,True,False,True,False,False,True,False,False,False,False,False,0.7,96.0,32.0,4.0,NaN,False,live
3,31,female,NaN,True,False,False,False,True,False,False,False,False,False,0.7,46.0,52.0,4.0,80.0,False,live
4,34,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,200.0,4.0,NaN,False,live
5,34,female,True,False,False,False,False,True,False,False,False,False,False,0.9,95.0,28.0,4.0,75.0,False,live
6,51,female,False,False,True,False,True,True,False,True,True,False,False,NaN,NaN,NaN,NaN,NaN,False,die
7,23,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,NaN,NaN,NaN,False,live
8,39,female,True,False,True,False,False,True,True,False,False,False,False,0.7,NaN,48.0,4.4,NaN,False,live
9,30,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,120.0,3.9,NaN,False,live

In [4]:
df.shape

(155, 20)

In [5]:
df.dtypes

age                  int64
sex                 object
steroid             object
antivirals            bool
fatigue             object
malaise             object
anorexia            object
liver_big           object
liver_firm          object
spleen_palpable     object
spiders             object
ascites             object
varices             object
bilirubin          float64
alk_phosphate      float64
sgot               float64
albumin            float64
protime            float64
histology             bool
class               object
dtype: object

In [6]:
numeric_df = df.select_dtypes(include=np.number).copy()
numeric_df

     age  bilirubin  alk_phosphate   sgot  albumin  protime
0     30        1.0           85.0   18.0      4.0      NaN
1     50        0.9          135.0   42.0      3.5      NaN
2     78        0.7           96.0   32.0      4.0      NaN
3     31        0.7           46.0   52.0      4.0     80.0
4     34        1.0            NaN  200.0      4.0      NaN
..   ...        ...            ...    ...      ...      ...
150   46        7.6            NaN  242.0      3.3     50.0
151   44        0.9          126.0  142.0      4.3      NaN
152   61        0.8           75.0   20.0      4.1      NaN
153   53        1.5           81.0   19.0      4.1     48.0
154   43        1.2          100.0   19.0      3.1     42.0

[155 rows x 6 columns]

In [7]:
numeric_df.dtypes

age                int64
bilirubin        float64
alk_phosphate    float64
sgot             float64
albumin          float64
protime          float64
dtype: object

In [8]:
numeric_df.mean()

age               41.200000
bilirubin          1.427517
alk_phosphate    105.325397
sgot              85.894040
albumin            3.817266
protime           61.852273
dtype: float64

In [15]:
# Replace missing values with the mean of each column
numeric_df = numeric_df.apply(lambda col: col.fillna(col.mean()))

In [11]:
# Ensure we select only numeric columns
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Fill missing values in numeric columns with the mean
df[numeric_cols] = df[numeric_cols].astype(float).apply(lambda col: col.fillna(col.mean()))

In [16]:
print(df.isnull().sum())  # Check missing values in all columns

age                 0
sex                 0
steroid             1
antivirals          0
fatigue             1
malaise             1
anorexia            1
liver_big          10
liver_firm         11
spleen_palpable     5
spiders             5
ascites             5
varices             5
bilirubin           0
alk_phosphate       0
sgot                0
albumin             0
protime             0
histology           0
class               0
dtype: int64